<?php

return array(
    'model' => 'Merchant',
    'search' => array(
        1 => array(
            'name' => 'name',
            'label' => '商户名',
            'boxname' => 'name',
            'type' => 'text',
            'schtp' => '0',
            'style' => '',
            'css' => '',
            ),
        2 => array(
            'name' => 'allow',
            'label' => '营业状态',
            'boxname' => 'allow',
            'type' => 'select',
            'schtp' => '1',
            'style' => '',
            'css' => '',
        ),
        3 => array(
            'name' => 'status',
            'label' => '入驻状态',
            'boxname' => 'status',
            'type' => 'select',
            'schtp' => '1',
            'style' => '',
            'css' => '',
        ),
        4 => array(
            'name' => 'phone',
            'label' => '联系电话',
            'boxname' => 'phone',
            'type' => 'select',
            'schtp' => '1',
            'style' => '',
            'css' => '',
        ),
        5 => array(
            'name' => 'type',
            'label' => '店铺类型',
            'boxname' => 'type',
            'type' => 'select',
            'schtp' => '1',
            'style' => '',
            'css' => '',
        ),
        6 => array(
            'name' => 'user_id',
            'label' => '用户id',
            'boxname' => 'user_id',
            'type' => 'text',
            'schtp' => '1',
            'style' => '',
            'css' => '',
        ),
        ),
    'usesql' => '0',
    'sql' => '',
    'sqlargs' => NULL,
    'usingfy' => '1',
    'orderby' => 'id desc',
);